supply:
  feed-interval: 5m #minutes

provider:
  name: xxx
  url: http://xxxprovider:8091/events
  timeout: 2000ms #milliseconds

mongodb: 
  name: FunDatabase
  uri: mongodb://localhost:27017
  
server.port: 8080