supply:
  feed-interval: 5m #minutes

provider:
  name: xxx
  url: http://xxxprovider:8091/events
  timeout: 2000ms #milliseconds

mongodb: 
  database.name: FunDataBase
  uri: ${MONGODB_URI}
  
server.port: 8080