app.time-to-feed: 10s #seconds

provider:
  name: xxx
  url: http://localhost:8091/events
  timeout: 2000ms #milliseconds

mongodb: 
  database.name: AcmeDataBase
  port: 27018
  uri: mongodb://localhost:${mongodb.port}
  
server.port: 8090