supply:
  feed-interval: 5m #minutes

provider:
  name: xxx
  url: https://xxx-provider.com/events
  timeout: 2000ms #milliseconds

mongodb:
  database.name: FunDataBase
  port: 27018
  uri: mongodb://localhost:${mongodb.port}

server.port: 8090