name: Development
run-name: ${{ github.actor }} is running Development workflow
on:
  push:
jobs:
  Push-action:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.3'
      - name: Update dependencies
        run: go mod download
      - name: Code generation
        run: |
          go install github.com/sunboyy/repogen@latest
          go generate ./adapters/*
          go install github.com/swaggo/swag/cmd/swag@latest
          swag init -dir cmd/userapi/  -parseDependency
      - name: Mocks generation
        run: |
          go install github.com/vektra/mockery/v3@latest
          make mocks
      - name: Tests execution
        run: |
          go clean -testcache
          go test ./...
